spring:
   datasource:
      url: jdbc:mysql://localhost:3306/querydsl
      username: root
      password: root
      dialect: MYSQL
   jpa:
      show-sql: true
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect 
      hibernate:
         ddl-auto: update