spring:
   datasource:
      url: jdbc:mysql://localhost:3306/jooq
      username: root
      password: root
      dialect: MYSQL
   jpa:
      show-sql: true
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect 
      hibernate:
         naming:
            physical-strategy: com.nacho.blog.jooq.jooqdemo.config.AllUpperCaseNamingStrategy
         ddl-auto: update
